# Generated by Django 4.2.5 on 2023-12-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('footer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'InProgress'), (4, 'EOL')], max_length=20)),
            ],
        ),
    ]
